# Generated by Django 3.2.6 on 2021-08-23 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('data_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('data_type', models.CharField(blank=True, choices=[('delayed_stocks', 'Delayed Stocks'), ('delayed_futures', 'Delayed Futures'), ('delayed_stocks_n_indexes', 'Delayed Stocks & Indexes'), ('delayed_stocks_indexes_n_futures', 'Delayed Stocks, Indexes & Futures'), ('real_time_stocks', 'Real-time Stocks'), ('real_time_futures', 'Real-time Futures'), ('real_time_stocks_n_indexes', 'Real-time Stocks & Indexes'), ('real_time_indexes', 'Real-time Indexes'), ('real_time_forex', 'Real-time Forex'), ('real_time_cryptocurrencies', 'Real-time Cryptocurrencies'), ('eod_stocks', 'EOD Stocks'), ('eod_futures', 'EOD Futures'), ('eod_stocks_n_certificates', 'EOD Stocks & Certificates'), ('eod_stocks_n_indexes', 'EOD Stocks & Indexes'), ('eod_stocks_futures_n_indexes', 'EOD Stocks, Indexes & Futures')], default='delayed_stocks', max_length=255, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country')),
            ],
        ),
    ]
