# Generated by Django 3.2.6 on 2021-10-14 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2000-10-10', help_text='Date on which User traded')),
                ('day', models.CharField(blank=True, help_text='Day on which User Traded', max_length=20, null=True)),
                ('profit_n_loss', models.DecimalField(decimal_places=2, default=0.0, help_text='Profit/Loss', max_digits=20)),
                ('charges', models.DecimalField(decimal_places=2, default=0.0, help_text='Broker Charges etc.', max_digits=20)),
                ('net_profit_n_loss', models.DecimalField(decimal_places=2, default=0.0, help_text='Net Profit/Loss after Charges', max_digits=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Active only in Swing Trades')),
                ('is_profit', models.BooleanField(default=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who did trade', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradingDayTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('Short', 'Short'), ('Long', 'Long')], default='Short', help_text='Position you took - Short/Long', max_length=255, null=True)),
                ('type_of_trade', models.CharField(blank=True, choices=[('Equity', 'Equity'), ('Futures', 'Futures'), ('Options', 'Options'), ('Forex', 'Forex'), ('Crypto', 'Crypto'), ('Other', 'Other')], default='Equity', help_text='Position you took - Short/Long', max_length=255, null=True)),
                ('symbol', models.CharField(blank=True, help_text='Instrument Symbol e.g., SBIN ', max_length=255, null=True)),
                ('title', models.CharField(blank=True, help_text='Intrument Name e.g., State bank of India', max_length=255, null=True)),
                ('quantity', models.IntegerField(default=0, help_text='Quantity placed in trade')),
                ('buy_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price at which instrument bought', max_digits=20)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price at which instrument sold', max_digits=20)),
                ('expected_target', models.DecimalField(decimal_places=2, default=0.0, help_text='Target Price', max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=2, default=0.0, help_text='Stop Loss', max_digits=20)),
                ('profit_n_loss', models.DecimalField(decimal_places=2, default=0.0, help_text='Profit/Loss', max_digits=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_intraday', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False, help_text='Active only in Swing Trades')),
                ('is_profit', models.BooleanField(default=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('trading_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.tradingday')),
            ],
        ),
    ]
