# Generated by Django 3.2.6 on 2021-10-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingday',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Broker Charges etc.', max_digits=20, null=True),
        ),
    ]
