# Generated by Django 3.2.6 on 2021-10-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20211018_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingday',
            name='is_front',
            field=models.BooleanField(default=True, help_text='If true, it means trades done after development of this platform.'),
        ),
    ]
