# Generated by Django 3.2.6 on 2021-10-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210901_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='capital_monu_final',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='final amount deposited for monu', max_digits=20),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='capital_monu_init',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Initial amount deposited for monu', max_digits=20),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='capital_sim_final',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='final amount deposited for sim', max_digits=20),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='capital_sim_init',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Initial amount deposited for sim', max_digits=20),
        ),
    ]
