# Generated by Django 3.2.6 on 2021-10-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211018_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='growth_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='growth_percent_monu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='growth_percent_sim',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
