# Generated by Django 3.2.6 on 2021-10-18 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20211018_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettingsEnabled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_screener_enabled', models.BooleanField(default=True)),
                ('forex_screener_enabled', models.BooleanField(default=True)),
                ('stock_screener_enabled', models.BooleanField(default=True)),
                ('market_quotes_enabled', models.BooleanField(default=True)),
                ('symbol_overview_enabled', models.BooleanField(default=True)),
                ('technical_chart_enabled', models.BooleanField(default=True)),
                ('technical_analysis_enabled', models.BooleanField(default=True)),
                ('forex_cross_rates_enabled', models.BooleanField(default=True)),
                ('forex_heat_map_enabled', models.BooleanField(default=True)),
                ('quote_overview_enabled', models.BooleanField(default=True)),
                ('ticker_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
